### ISSUE TITLE
Spaces with chunkwm

### ISSUE THREAD

**Issue by sealevelcain** [Amar1729/nerdbar.widget#3]
Is it possible for the spaces feature to support chunkwm? I tried to edit spaces.sh etc to call on /usr/bin/local/chunkc instead of kwmc but that didn't work. I don't really know what I'm doing so past that I don't have any other ideas.

**Comment by Amar1729** [comment]
Unfortunately I don't use chunkwm (yet), so I'm not entirely sure how this would work. From [this issue](https://github.com/koekeishiya/chunkwm/issues/38) it seems that the `chunkwm query` system works differently from `kwmc query` , but one of the commenters wrote [this gist](https://gist.github.com/crisidev/7adc01bad32bea39bf245f339e215942) that may work. 

With that gist, you'd save it in the same directory, and edit the call in `spaces.sh` to something like: 
 
`python chunkwm-query.py -d`

**Comment by Amar1729** [comment]
todo - update this sometime over the weekend
Relevant commands:
```
chunkc tiling::query --desktop id
chunkc tiling::query --desktop mode
```

**Comment by Amar1729** [comment]
Super late fix, but [this commit](https://github.com/Amar1729/nerdbar.widget/commit/840eca217459beeb01c9705243459bb0ecb90ef6) finally has chunkwm support. Took a while to find the proper chunkwm commands.
