### ISSUE TITLE
What is this file?

### ISSUE THREAD

**Issue by bravecorvus** [Amar1729/nerdbar.widget#4]
Please provide a real file at this link:
![img](https://66.media.tumblr.com/e8bae00e27c46c8d39694c83e1c0f47a/tumblr_pp5z6oSszC1s5a4bko1_1280.png)

**Comment by Amar1729** [comment]
right so the colors are loaded assuming you have color generation done by [`pywal`](https://github.com/dylanaraps/pywal).

If you run that once, you can then manually create this symlink:
```bash
cd ./styles
ln -s ~/.cache/wal/colors.css ./colors-wal.css
```
